Adding Data to a netCDF File (1D, 2D, 3D)

In [1]:
!pip install xarray

In [6]:
# importing libraries
import xarray as xr

In [4]:
# intializing dataset
xrds = xr.Dataset()
xrds



<xarray.Dataset> Size: 0B
Dimensions:  ()
Data variables:
    *empty*

In [8]:
depths = [0, 10, 20, 25]

xrds = xr.Dataset(
    coords = {
        'depth': depths
    }
)

xrds

<xarray.Dataset> Size: 32B
Dimensions:  (depth: 4)
Coordinates:
  * depth    (depth) int64 32B 0 10 20 25
Data variables:
    *empty*

In [10]:
depths = [0, 10, 20, 25]
latitude = [12,45,23]
longitude = [39,42,23]

xrds = xr.Dataset(
    coords = {
        'depth': depths,
        'latitude': latitude,
        'longitude': longitude
    }
)

xrds

<xarray.Dataset> Size: 80B
Dimensions:    (depth: 4, latitude: 3, longitude: 3)
Coordinates:
  * depth      (depth) int64 32B 0 10 20 25
  * latitude   (latitude) int64 24B 12 45 23
  * longitude  (longitude) int64 24B 39 42 23
Data variables:
    *empty*

In [16]:
# adding time

import numpy as np


depths = [0, 10, 20, 25]
latitude = [12,45,23]
longitude = [39,42,23]

start = np.datetime64('2024-01-01T00:00:00')
end = start + np.timedelta64(24, 'h')
timestamps = np.arange(start, end, np.timedelta64(1, 'h'))

seconds_since_start = (timestamps - start) / np.timedelta64(1, 's')
seconds_since_start = seconds_since_start.astype(np.float64)
print(seconds_since_start)

xrds = xr.Dataset(
    coords = {
        'depth': depths,
        'latitude': latitude,
        'longitude': longitude,
        'time':
    }
)

xrds

[    0.  3600.  7200. 10800. 14400. 18000. 21600. 25200. 28800. 32400.
 36000. 39600. 43200. 46800. 50400. 54000. 57600. 61200. 64800. 68400.
 72000. 75600. 79200. 82800.]


<ipython-input-16-5757e42020d0>:18: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  xrds = xr.Dataset(


<xarray.Dataset> Size: 272B
Dimensions:    (depth: 4, latitude: 3, longitude: 3, time: 24)
Coordinates:
  * depth      (depth) int64 32B 0 10 20 25
  * latitude   (latitude) int64 24B 12 45 23
  * longitude  (longitude) int64 24B 39 42 23
  * time       (time) datetime64[ns] 192B 2024-01-01 ... 2024-01-01T23:00:00
Data variables:
    *empty*

In [18]:
# Adding data variable

import numpy as np


depths = [0, 10, 20, 25]
latitude = [12,45,23]
longitude = [39,42,23]

start = np.datetime64('2024-01-01T00:00:00')
end = start + np.timedelta64(24, 'h')
timestamps = np.arange(start, end, np.timedelta64(1, 'h'))

seconds_since_start = (timestamps - start) / np.timedelta64(1, 's')
seconds_since_start = seconds_since_start.astype(np.float64)

chlorophyll_a = [12.56,45.6,45.5,12] #4 points, one for each depths



xrds = xr.Dataset(
    coords = {
        'depth': depths,
        'latitude': latitude,
        'longitude': longitude,
        'time': seconds_since_start
    },
    data_vars = {
        'chlorophyll_a': ('depth', chlorophyll_a)
    }
)

xrds

<xarray.Dataset> Size: 304B
Dimensions:        (depth: 4, latitude: 3, longitude: 3, time: 24)
Coordinates:
  * depth          (depth) int64 32B 0 10 20 25
  * latitude       (latitude) int64 24B 12 45 23
  * longitude      (longitude) int64 24B 39 42 23
  * time           (time) float64 192B 0.0 3.6e+03 7.2e+03 ... 7.92e+04 8.28e+04
Data variables:
    chlorophyll_a  (depth) float64 32B 12.56 45.6 45.5 12.0

In [26]:
# Adding data variables having more than one D

import numpy as np


depths = [0, 10, 20, 25]
latitude = [12,45,23]
longitude = [39,42,23]

start = np.datetime64('2024-01-01T00:00:00')
end = start + np.timedelta64(24, 'h')
timestamps = np.arange(start, end, np.timedelta64(1, 'h'))

seconds_since_start = (timestamps - start) / np.timedelta64(1, 's')
seconds_since_start = seconds_since_start.astype(np.float64)

chlorophyll_a = [12.56,45.6,45.5,12] #4 points, one for each depths

wind_speed = np.random.randint(0,10,size=(3,3)) #adding 2d array of wind speed
print(wind_speed)

xrds = xr.Dataset(
    coords = {
        'depth': depths,
        'latitude': latitude,
        'longitude': longitude,
        'time': seconds_since_start
    },
    data_vars = {
        'chlorophyll_a': ('depth', chlorophyll_a),
        'wind_speed': (['latitude', 'longitude'], wind_speed)
    }
)

xrds


[[5 3 8]
 [7 5 9]
 [8 1 1]]


<xarray.Dataset> Size: 376B
Dimensions:        (depth: 4, latitude: 3, longitude: 3, time: 24)
Coordinates:
  * depth          (depth) int64 32B 0 10 20 25
  * latitude       (latitude) int64 24B 12 45 23
  * longitude      (longitude) int64 24B 39 42 23
  * time           (time) float64 192B 0.0 3.6e+03 7.2e+03 ... 7.92e+04 8.28e+04
Data variables:
    chlorophyll_a  (depth) float64 32B 12.56 45.6 45.5 12.0
    wind_speed     (latitude, longitude) int64 72B 5 3 8 7 5 9 8 1 1

In [29]:
print(xrds['wind_speed'].values)

[[5 3 8]
 [7 5 9]
 [8 1 1]]


In [32]:
# Adding data variables having more than one D

# Adding data variable

# adding time

import numpy as np


depths = [0, 10, 20, 25]
latitude = [12,45]
longitude = [39,42,23]

start = np.datetime64('2024-01-01T00:00:00')
end = start + np.timedelta64(24, 'h')
timestamps = np.arange(start, end, np.timedelta64(1, 'h'))

seconds_since_start = (timestamps - start) / np.timedelta64(1, 's')
seconds_since_start = seconds_since_start.astype(np.float64)

chlorophyll_a = [12.56,45.6,45.5,12] #4 points, one for each depths

wind_speed = np.random.randint(0,10,size=(2,3)) #adding 2d array of wind speed
print(wind_speed)

xrds = xr.Dataset(
    coords = {
        'depth': depths,
        'latitude': latitude,
        'longitude': longitude,
        'time': seconds_since_start
    },
    data_vars = {
        'chlorophyll_a': ('depth', chlorophyll_a),
        'wind_speed': (['latitude', 'longitude'], wind_speed)
    }
)

xrds


[[8 5 0]
 [7 4 2]]


<xarray.Dataset> Size: 344B
Dimensions:        (depth: 4, latitude: 2, longitude: 3, time: 24)
Coordinates:
  * depth          (depth) int64 32B 0 10 20 25
  * latitude       (latitude) int64 16B 12 45
  * longitude      (longitude) int64 24B 39 42 23
  * time           (time) float64 192B 0.0 3.6e+03 7.2e+03 ... 7.92e+04 8.28e+04
Data variables:
    chlorophyll_a  (depth) float64 32B 12.56 45.6 45.5 12.0
    wind_speed     (latitude, longitude) int64 48B 8 5 0 7 4 2

In [33]:
# Adding 3d Temp data

import numpy as np


depths = [0, 10, 20, 25]
latitude = [12,45]
longitude = [39,42,23]

start = np.datetime64('2024-01-01T00:00:00')
end = start + np.timedelta64(24, 'h')
timestamps = np.arange(start, end, np.timedelta64(1, 'h'))

seconds_since_start = (timestamps - start) / np.timedelta64(1, 's')
seconds_since_start = seconds_since_start.astype(np.float64)

chlorophyll_a = [12.56,45.6,45.5,12] #4 points, one for each depths

wind_speed = np.random.randint(0,10,size=(2,3)) #adding 2d array of wind speed

temp = np.random.randint(0,10,size=(len(latitude), len(longitude), len(depths))) #adding 3d array of temp
print(temp)

xrds = xr.Dataset(
    coords = {
        'depth': depths,
        'latitude': latitude,
        'longitude': longitude,
        'time': seconds_since_start
    },
    data_vars = {
        'chlorophyll_a': ('depth', chlorophyll_a),
        'wind_speed': (['latitude', 'longitude'], wind_speed),
        'temp': (['latitude', 'longitude', 'depth'], temp)
    }
)

xrds


[[[3 2 7 9]
  [1 5 1 8]
  [2 6 4 7]]

 [[5 5 0 6]
  [3 2 9 3]
  [2 9 6 9]]]


<xarray.Dataset> Size: 536B
Dimensions:        (depth: 4, latitude: 2, longitude: 3, time: 24)
Coordinates:
  * depth          (depth) int64 32B 0 10 20 25
  * latitude       (latitude) int64 16B 12 45
  * longitude      (longitude) int64 24B 39 42 23
  * time           (time) float64 192B 0.0 3.6e+03 7.2e+03 ... 7.92e+04 8.28e+04
Data variables:
    chlorophyll_a  (depth) float64 32B 12.56 45.6 45.5 12.0
    wind_speed     (latitude, longitude) int64 48B 2 2 8 3 2 8
    temp           (latitude, longitude, depth) int64 192B 3 2 7 9 1 ... 2 9 6 9